### ISSUE TITLE
USER STORY: Anom feedback

### ISSUE THREAD

**Issue by gordonbates** [gordonbates/my-first-agile-project#2]
User Story: In order to provide **anonymous feedback**  as a **user**, I can choose to **hide my identity in the poll response**.

Acceptance Criteria:

  - The option should be provided as a checkbox
  - The checkbox should be “checked” by default
  - The option should appear next to the submit button
  - After submitting the default submission confirmation should be adjusted to include the user name.

# Tasks

- [ ] Update the admin module view: the poll design (HTML and CSS) to include
date picker
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon"
- [ ] Create a Javascript function to validate the expiry date is at least after 3 days.
- [ ] Create a job to check expired Polls everyday at 11:59 PM and Hide them
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
